### ISSUE TITLE
Code overlay on visual output

### ISSUE THREAD

**Issue by hellocatfood** [edne/pineal#3]
Could Pineal have a feature similar to Fluxus that overlays the code being written onto the graphics window?

**Comment by edne** [comment]
Yes!
Currently it would be messy to use with the feedback effects, but I'm refactoring the back-end part to allow multiple layers.
So in the near future it will be a feature :)

**Comment by hellocatfood** [comment]
Nice! Although having the option for the text to be part of feedback effects could be nice as well. Makes the text part of the visuals.

**Comment by edne** [comment]
Now it can be done sending text via OSC (via the [osc-text](https://pineal.readthedocs.io/en/latest/dsl/entities.html#osc-text) function)
