### ISSUE TITLE
High CPU Usage/Laptop heating up

### ISSUE THREAD

**Issue by theseanco** [edne/pineal#5]
I'm running pineal with hy 0.11.0 and CPython 2.7.6 on OSX 10.10.1

It works great, but there's abnormally high CPU usage reported from the activity monitor, and my laptop quickly starts heating up an awful lot, far more than any other program i use. (the inside of the laptop has had a recent blowout, so it's not a physical issue, and i don't have this issue with any other programs). I installed wxpython under the guidance of the terminal error i got when i first ran pineal, but this made no difference to the high CPU usage/temps. Not sure why this is.

Also the python process registers as 'not responding', not sure if this is significant - it runs fine regardless. 

![screen shot 2015-06-01 at 18 32 33](https://cloud.githubusercontent.com/assets/8597971/7918911/b09ad3b0-088c-11e5-9a94-a6b6768a3b5d.png)

**Comment by edne** [comment]
The high usage of CPU is a normal behavior, but I'm working to reduce it

**Comment by edne** [comment]
Now it should use cpu as any other OpenFrameworks app.
